// app.slint

import {
    Button,
    VerticalBox,
    ListView,
    HorizontalBox,
} from "std-widgets.slint";

// Определяем структуру для туннеля
export struct FolderItem {
    name: string,
    path: string,
}

export component AppWin inherits Window {
    in-out property <[FolderItem]> folders;

    callback clear_folder(int);

    callback file-new();
    callback file-open();
    callback quit();

//    width: 600px;
//    height: 800px;
    min-width: 600px;
    min-height: 400px;

    title: "Очистка папок";

    VerticalBox {
        ListView {
            for folder[i] in folders: HorizontalBox {
                Text {
                    text: folder.name;
                    vertical-alignment: center;
                }

                Text {
                    text: folder.path;
                    vertical-alignment: center;
                }

                Button {
                    text: "Очистить";
                    clicked => {
                        clear_folder(i);
                    }
                }
            }
        }
    }
}