// app.slint
import {
    Button,
    VerticalBox,
    ListView,
    HorizontalBox,
} from "std-widgets.slint";

// Определяем структуру для папок
export struct FolderItem {
    name: string,
    path: string,
}

export component AppWin inherits Window {
    in property <string> app-name;
    in property <string> version;
    in-out property <[FolderItem]> folders;
    in property <[string]> logs;

    callback clear_folder(int);

    callback file-new();
    callback file-open();
    callback quit();
    callback update();
    callback show-about();

    //    width: 600px;
//    height: 800px;
    min-width: 600px;
    min-height: 400px;

    title: "Очистка папок";

    MenuBar {
        Menu {
            title: @tr("Список");
            MenuItem {
                title: @tr("Новый список");
                activated => {
                    file-new();
                }
            }

            MenuItem {
                title: @tr("Open");
                activated => {
                    file-open();
                }
            }
        }

        Menu {
            title: @tr("Edit");
            MenuItem {
                title: @tr("Copy");
            }

            MenuItem {
                title: @tr("Paste");
            }

            MenuSeparator { }

            Menu {
                title: @tr("Find");
                MenuItem {
                    title: @tr("Find in document...");
                }

                MenuItem {
                    title: @tr("Find Next");
                }

                MenuItem {
                    title: @tr("Find Previous");
                }
            }
        }

        Menu {
            title: @tr("О программе...");
            MenuItem {
                title: @tr("Версия: ") + root.version;
//                text: "Версия: " + version;
            }

            MenuItem {
                title: @tr("Обновить");
                activated => {
                    update();
                }
            }
        }
    }

    Rectangle {
        VerticalBox {
            ListView {
                min-height: 80px;
//                max-height: 250px;
                for folder[i] in folders: HorizontalBox {
                    Text {
                        text: folder.name;
                        vertical-alignment: center;
                    }

                    Text {
                        text: folder.path;
                        vertical-alignment: center;
                    }

                    Button {
                        text: "Очистить";
                        clicked => {
                            clear_folder(i);
                        }
                    }
                }
            }

            //        Rectangle {
//            height: 2px;
//            background: gray;
//        }

            ListView {
                min-height: 250px;
//                width: parent.width;
//                height: parent.height;
                for log in logs: Text {
                    text: log;
                    wrap: word-wrap;
                }
            }
        }
    }
}
