// app.slint

import { VerticalBox, AboutSlint } from "std-widgets.slint";
//import { Palette, StyleMetrics } from "std-widgets.slint";
//import { MenuBar, Menu, MenuItem, VerticalLayout } from "std-widgets.slint";

export component AppWin inherits Window {
    width: 600px;
    height: 800px;
    title: "Очистка папок";

    callback file-new();
    callback file-open();
    callback quit();

    MenuBar {
        Menu {
            title: @tr("File");
            MenuItem {
                title: @tr("New");
                activated => {
                    file-new();
                }
            }

            MenuItem {
                title: @tr("Open");
                activated => {
                    file-open();
                }
            }
        }

        Menu {
            title: @tr("Edit");
            MenuItem {
                title: @tr("Copy");
            }

            MenuItem {
                title: @tr("Paste");
            }

            MenuSeparator { }

            Menu {
                title: @tr("Find");
                MenuItem {
                    title: @tr("Find in document...");
                }

                MenuItem {
                    title: @tr("Find Next");
                }

                MenuItem {
                    title: @tr("Find Previous");
                }
            }
        }

        Menu {
            title: @tr("About");
//             AboutSlint {};
        }
    }

    VerticalBox {
        padding: 20px;

        Rectangle {
            background: #b9bec4;
            border-width: 4px;
        }
    }
//    AboutSlint {}
}
