import {
    Button,
    VerticalBox,
    ListView,
    HorizontalBox,
    StandardButton,
} from "std-widgets.slint";

// Определяем структуру для папок
export struct FolderItem {
    name: string,
    path: string,
}

export component AppWin inherits Window {
    in-out property <[FolderItem]> folders: [
        { name: "Disk C:/Temp", path: "C:/Temp" },
        { name: "Disk D:/Temp", path: "D:/Temp" },
        { name: "Disk E:/Temp", path: "E:/Temp" }
    ];
    in property <string> app-name;
    in property <string> version;
    in property <[string]> logs: ["Строка 1", "Строка 2", "Строка 3", "Строка 4"];

    callback clear_folder(int);

    callback folder-new();
    callback update();
    callback quit();

    min-width: 600px;
    min-height: 780px;

    title: "Очистка папок";

    MenuBar {
        Menu {
            title: @tr("Файл");
            MenuItem {
                title: @tr("Новая папка");
                activated => {
                    folder-new();
                }
            }

            MenuItem {
                title: @tr("Выход");
                activated => {
                    quit();
                }
            }
        }

        Menu {
            title: @tr("О программе...");
            MenuItem {
                title: @tr("Версия: ") + root.version;
                activated => {
                    update();
                }
            }
        }
    }

    Rectangle {
        VerticalBox {
            padding: 10px;
            ListView {
                max-height: 144px;
                for folder[i] in folders: HorizontalBox {
                    Text {
                        text: folder.name;
                        vertical-alignment: center;
                    }

                    Text {
                        text: folder.path;
                        vertical-alignment: center;
                    }

                    Button {
                        text: "Очистить";
                        clicked => {
                            clear_folder(i);
                        }
                    }
                }
            }

            Rectangle {
                height: 2px;
                background: gray;
            }

            ListView {
                for log in logs: Text {
                    x: 0px;
                    text: log;
                    wrap: word-wrap;
                }
            }

            HorizontalBox {
                alignment: end;
                StandardButton {
                    kind: close;
                    clicked() => {
                        quit();
                    }
                }
            }
        }
    }
}
